### ISSUE TITLE
color to xcolor

### ISSUE THREAD

**Issue by ysBach** [yangcht/AA-bibstyle-with-hyperlink#1]
\usepackage{color}

Gave this warning: [Incompatible color definition](https://tex.stackexchange.com/questions/150369/incompatible-color-definition-when-using-tikz-with-color-package)

Changing it to xcolor removed the warning...

    \usepackage{xcolor}

**Comment by yangcht** [comment]
Interesting. I think this might be useful for others if they encounter the same warnings. I am wondering, besides the warning, does it affect the compiled PDF?

**Comment by yangcht** [comment]
fixed.
