### ISSUE TITLE
remove breakurl?

### ISSUE THREAD

**Issue by ysBach** [yangcht/AA-bibstyle-with-hyperlink#2]
using breakurl gave me 

[Warning: You are using breakurl while processing via pdflatex](https://tex.stackexchange.com/questions/279402/package-breakurl-warning-you-are-using-breakurl-while-processing-via-pdflatex)

I just removed the usepackage and it worked fine.

**Comment by yangcht** [comment]
Thanks for checking this. This bibstyle requires the entries to be generated from ADS or at least have a similar format as the ADS ones.
